language: node_js

node_js:
    - "6"
    - "node"
sudo: false
before_install:
    - npm install -g eslint
install:
    - npm install
script:
    - npm run analyze-coverage
    - npm run send-coverage
    - npm run browserify